pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

rootProject.name = 'MinecraftDependencyDownload'

[
    'common',
    'bukkit', 'bukkit:loader',
    'bungee', 'bungee:loader',
    'fabric',
    'forge', 'forge:loader',
    'neoforge', 'neoforge:loader',
    'velocity'
].each {
    include it
    findProject(':' + it).name = String.join('-', it.split(':'))
}
