plugins {
    id 'net.neoforged.moddev' version '2.0.134'
    id("java-library")
}

java {
    sourceCompatibility = 21
    targetCompatibility = 21
}

dependencies {
    api project(':common')
    api 'dev.vankka:dependencydownload-jarinjar-loader:' + dependencyDownloadVersion
}

neoForge {
    version = "21.11.17-beta"
}