name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Deploy with Gradle
        run: |
          echo "ossrhUsername=$SONATYPE_USERNAME" >> gradle.properties
          echo "ossrhPassword=$SONATYPE_PASSWORD" >> gradle.properties
          ./gradlew publish --no-daemon
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
          SONATYPE_KEY_PASS: ${{ secrets.SONATYPE_KEY_PASS }}
